version: 0.2

env:
  parameter-store:
     DOCKER_USERNAME: /docker/username
     DOCKER_PASSWORD: /docker/password
     DOCKER_URL: /docker/url
phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Building Docker Image"
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_URL"
      - docker build -t "$DOCKER_URL/$DOCKER_USERNAME/aws-pipeline-flask" .
      - docker push "docker.io/$DOCKER_USERNAME/aws-pipeline-flask"
  post_build:
    commands:
      - echo "Build and Push completed"
